/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// MonitorType : 
type MonitorType string

// List of MonitorType
const (
	HTTP_MonitorType MonitorType = "Http"
	HTTPS_MonitorType MonitorType = "Https"
	CONNECT_MonitorType MonitorType = "Connect"
	PING_MonitorType MonitorType = "Ping"
	POP3_MonitorType MonitorType = "POP3"
	SMTP_MonitorType MonitorType = "SMTP"
	FTP_MonitorType MonitorType = "FTP"
	MY_SQL_MonitorType MonitorType = "MySQL"
	MSSQL_MonitorType MonitorType = "MSSQL"
	WEBSERVICE_HTTP_MonitorType MonitorType = "WebserviceHttp"
	WEBSERVICE_HTTPS_MonitorType MonitorType = "WebserviceHttps"
	TRANSACTION_MonitorType MonitorType = "Transaction"
	DNS_MonitorType MonitorType = "DNS"
	FULL_PAGE_CHECK_MonitorType MonitorType = "FullPageCheck"
	REAL_BROWSER_CHECK_MonitorType MonitorType = "RealBrowserCheck"
	CERTIFICATE_MonitorType MonitorType = "Certificate"
	SFTP_MonitorType MonitorType = "SFTP"
	MULTI_STEP_API_MonitorType MonitorType = "MultiStepApi"
	IMAP_MonitorType MonitorType = "IMAP"
)
