/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type MsaStep struct {
	Url string `json:"Url,omitempty"`
	Method string `json:"Method,omitempty"`
	Body string `json:"Body,omitempty"`
	RequestHeaders []ApiHttpHeaderValue `json:"RequestHeaders,omitempty"`
	Variables []ApiVariableDefinition `json:"Variables,omitempty"`
	Assertions []ApiAssertion `json:"Assertions,omitempty"`
	Name string `json:"Name,omitempty"`
	Disabled bool `json:"Disabled"`
	UseFixedClientCertificate bool `json:"UseFixedClientCertificate"`
	Authentication *ApiAuthenticationInfo `json:"Authentication,omitempty"`
	IgnoreCertificateErrors bool `json:"IgnoreCertificateErrors"`
	ClientCertificateVaultItem string `json:"ClientCertificateVaultItem,omitempty"`
	Delay int32 `json:"Delay"`
	StepType *MsaStepType `json:"StepType"`
}
