/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// Checkpoint server
type CheckpointServer struct {
	// The Id of the checkpoint server
	CheckpointServerId int32 `json:"CheckpointServerId"`
	// The IPv4 address of the checkpoint server
	Ipv4Address string `json:"Ipv4Address,omitempty"`
	// The IPv6 address of this checkpoint server
	Ipv6Address string `json:"Ipv6Address,omitempty"`
	// The list of capabilities of this checkpoint server
	Capabilities []CapabilityFilter `json:"Capabilities,omitempty"`
}
