/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// SubStepType : 
type SubStepType string

// List of SubStepType
const (
	NAVIGATE_SubStepType SubStepType = "Navigate"
	CLICK_SubStepType SubStepType = "Click"
	SET_SubStepType SubStepType = "Set"
	TEST_SubStepType SubStepType = "Test"
	SCRIPT_SubStepType SubStepType = "Script"
	HOVER_SubStepType SubStepType = "Hover"
	SCREENSHOT_SubStepType SubStepType = "Screenshot"
	SCROLL_TO_SubStepType SubStepType = "ScrollTo"
	WAIT_FOR_ELEMENT_SubStepType SubStepType = "WaitForElement"
	SWITCH_TO_FRAME_SubStepType SubStepType = "SwitchToFrame"
	SWITCH_TO_TAB_SubStepType SubStepType = "SwitchToTab"
)
