/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// ApiSourceType : 
type ApiSourceType string

// List of ApiSourceType
const (
	NONE_ApiSourceType ApiSourceType = "None"
	CONSTANT_ApiSourceType ApiSourceType = "Constant"
	VARIABLE_ApiSourceType ApiSourceType = "Variable"
	RESPONSE_STATUS_CODE_ApiSourceType ApiSourceType = "ResponseStatusCode"
	RESPONSE_STATUS_DESCRIPTION_ApiSourceType ApiSourceType = "ResponseStatusDescription"
	RESPONSE_BODY_JSON_ApiSourceType ApiSourceType = "ResponseBodyJson"
	RESPONSE_COMPLETED_ApiSourceType ApiSourceType = "ResponseCompleted"
	RESPONSE_BODY_TEXT_ApiSourceType ApiSourceType = "ResponseBodyText"
	FAIL_ApiSourceType ApiSourceType = "Fail"
	CONTENT_LENGTH_CALCULATED_ApiSourceType ApiSourceType = "ContentLengthCalculated"
	DURATION_ApiSourceType ApiSourceType = "Duration"
	SUM_ApiSourceType ApiSourceType = "Sum"
	CONCATENATION_ApiSourceType ApiSourceType = "Concatenation"
	TO_BASE64_ApiSourceType ApiSourceType = "ToBase64"
	TO_SHA1_HEX_ApiSourceType ApiSourceType = "ToSHA1Hex"
	TO_MD5_HEX_ApiSourceType ApiSourceType = "ToMD5Hex"
	RESPONSE_BODY_XML_ApiSourceType ApiSourceType = "ResponseBodyXml"
	RESPONSE_HEADER_ApiSourceType ApiSourceType = "ResponseHeader"
	COOKIE_ApiSourceType ApiSourceType = "Cookie"
	VARIABLES_RESOLVED_ApiSourceType ApiSourceType = "VariablesResolved"
	CUMULATIVE_DURATION_ApiSourceType ApiSourceType = "CumulativeDuration"
	RESPONSE_HAS_EXCEPTION_ApiSourceType ApiSourceType = "ResponseHasException"
)
