/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// PresetPeriodTypeWithExclusive : 
type PresetPeriodTypeWithExclusive string

// List of PresetPeriodTypeWithExclusive
const (
	CURRENT_DAY_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "CurrentDay"
	CURRENT_WEEK_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "CurrentWeek"
	CURRENT_MONTH_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "CurrentMonth"
	CURRENT_YEAR_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "CurrentYear"
	PREVIOUS_DAY_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "PreviousDay"
	PREVIOUS_WEEK_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "PreviousWeek"
	PREVIOUS_MONTH_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "PreviousMonth"
	PREVIOUS_YEAR_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "PreviousYear"
	LAST24_HOURS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last24Hours"
	LAST48_HOURS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last48Hours"
	LAST7_DAYS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last7Days"
	LAST30_DAYS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last30Days"
	LAST60_DAYS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last60Days"
	LAST90_DAYS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last90Days"
	LAST365_DAYS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last365Days"
	LAST3_MONTHS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last3Months"
	LAST6_MONTHS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last6Months"
	LAST12_MONTHS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last12Months"
	LAST24_MONTHS_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last24Months"
	LAST24_HOURS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last24HoursExcl"
	LAST48_HOURS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last48HoursExcl"
	LAST7_DAYS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last7DaysExcl"
	LAST30_DAYS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last30DaysExcl"
	LAST60_DAYS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last60DaysExcl"
	LAST90_DAYS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last90DaysExcl"
	LAST365_DAYS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last365DaysExcl"
	LAST3_MONTHS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last3MonthsExcl"
	LAST6_MONTHS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last6MonthsExcl"
	LAST12_MONTHS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last12MonthsExcl"
	LAST24_MONTHS_EXCL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "Last24MonthsExcl"
	ALL_PresetPeriodTypeWithExclusive PresetPeriodTypeWithExclusive = "All"
)
