/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

import (
	"time"
)

type CertificateArchive struct {
	// The issuer of this certificate
	Issuer string `json:"Issuer,omitempty"`
	// The start date of this certificate
	NotBefore time.Time `json:"NotBefore"`
	// The certificate expiry date
	NotAfter time.Time `json:"NotAfter"`
	// Used to specify a new or changed password. The value will be encrypted when stored, and will not be displayed when a CertificateArchive is retrieved.
	Password string `json:"Password,omitempty"`
	// Used to specify the certificate content as a base64 string. The value will be encrypted when stored, and will not be displayed when a CertificateArchive is retrieved.
	ArchiveData string `json:"ArchiveData,omitempty"`
}
