/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// ThrottlingValue : 
type ThrottlingValue string

// List of ThrottlingValue
const (
	ADSL_ThrottlingValue ThrottlingValue = "Adsl"
	FIBER_ThrottlingValue ThrottlingValue = "Fiber"
	CABLE_ThrottlingValue ThrottlingValue = "Cable"
	2G__ThrottlingValue ThrottlingValue = "2G"
	3G__ThrottlingValue ThrottlingValue = "3G"
	4G__ThrottlingValue ThrottlingValue = "4G"
)
