/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// CapabilityFilter : 
type CapabilityFilter string

// List of CapabilityFilter
const (
	I_PV6_CapabilityFilter CapabilityFilter = "IPv6"
	NATIVE_I_PV6_CapabilityFilter CapabilityFilter = "NativeIPv6"
	PRIMARY_SERVER_CapabilityFilter CapabilityFilter = "PrimaryServer"
)
