/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// SftpAction : 
type SftpAction string

// List of SftpAction
const (
	CONNECT_ONLY_SftpAction SftpAction = "ConnectOnly"
	TEST_FILE_EXISTS_SftpAction SftpAction = "TestFileExists"
	TEST_FILE_DOES_NOT_EXIST_SftpAction SftpAction = "TestFileDoesNotExist"
	DOWN_LOAD_FILE_SftpAction SftpAction = "DownLoadFile"
)
