/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// ApiComparisonType : 
type ApiComparisonType string

// List of ApiComparisonType
const (
	EQUAL_ApiComparisonType ApiComparisonType = "Equal"
	DOES_NOT_EQUAL_ApiComparisonType ApiComparisonType = "DoesNotEqual"
	CONTAINS_TEXT_ApiComparisonType ApiComparisonType = "ContainsText"
	DOES_NOT_CONTAIN_TEXT_ApiComparisonType ApiComparisonType = "DoesNotContainText"
	SHOULD_BE_IGNORED_ApiComparisonType ApiComparisonType = "ShouldBeIgnored"
	LESS_THAN_ApiComparisonType ApiComparisonType = "LessThan"
	GREATER_THAN_ApiComparisonType ApiComparisonType = "GreaterThan"
	LESS_THAN_OR_EQUAL_ApiComparisonType ApiComparisonType = "LessThanOrEqual"
	GREATER_THAN_OR_EQUAL_ApiComparisonType ApiComparisonType = "GreaterThanOrEqual"
	IS_NOT_EMPTY_ApiComparisonType ApiComparisonType = "IsNotEmpty"
)
