/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// DayOfWeek : 
type DayOfWeek string

// List of DayOfWeek
const (
	SUNDAY_DayOfWeek DayOfWeek = "Sunday"
	MONDAY_DayOfWeek DayOfWeek = "Monday"
	TUESDAY_DayOfWeek DayOfWeek = "Tuesday"
	WEDNESDAY_DayOfWeek DayOfWeek = "Wednesday"
	THURSDAY_DayOfWeek DayOfWeek = "Thursday"
	FRIDAY_DayOfWeek DayOfWeek = "Friday"
	SATURDAY_DayOfWeek DayOfWeek = "Saturday"
)
