/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type MonitorGroup struct {
	// The unique identifier of this monitor group
	MonitorGroupGuid string `json:"MonitorGroupGuid"`
	// The descriptive name of this probe group
	Description string `json:"Description,omitempty"`
	// Indicates whether this is the default group for all probes
	IsAll bool `json:"IsAll"`
}
