/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends
// PresetPeriodType : 
type PresetPeriodType string

// List of PresetPeriodType
const (
	CURRENT_DAY_PresetPeriodType PresetPeriodType = "CurrentDay"
	CURRENT_WEEK_PresetPeriodType PresetPeriodType = "CurrentWeek"
	CURRENT_MONTH_PresetPeriodType PresetPeriodType = "CurrentMonth"
	CURRENT_YEAR_PresetPeriodType PresetPeriodType = "CurrentYear"
	PREVIOUS_DAY_PresetPeriodType PresetPeriodType = "PreviousDay"
	PREVIOUS_WEEK_PresetPeriodType PresetPeriodType = "PreviousWeek"
	PREVIOUS_MONTH_PresetPeriodType PresetPeriodType = "PreviousMonth"
	PREVIOUS_YEAR_PresetPeriodType PresetPeriodType = "PreviousYear"
	LAST24_HOURS_PresetPeriodType PresetPeriodType = "Last24Hours"
	LAST48_HOURS_PresetPeriodType PresetPeriodType = "Last48Hours"
	LAST7_DAYS_PresetPeriodType PresetPeriodType = "Last7Days"
	LAST30_DAYS_PresetPeriodType PresetPeriodType = "Last30Days"
	LAST60_DAYS_PresetPeriodType PresetPeriodType = "Last60Days"
	LAST90_DAYS_PresetPeriodType PresetPeriodType = "Last90Days"
	LAST365_DAYS_PresetPeriodType PresetPeriodType = "Last365Days"
	LAST3_MONTHS_PresetPeriodType PresetPeriodType = "Last3Months"
	LAST6_MONTHS_PresetPeriodType PresetPeriodType = "Last6Months"
	LAST12_MONTHS_PresetPeriodType PresetPeriodType = "Last12Months"
	LAST24_MONTHS_PresetPeriodType PresetPeriodType = "Last24Months"
	ALL_PresetPeriodType PresetPeriodType = "All"
)
