/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

import (
	"time"
)

type StatisticsAttributes struct {
	StartDateTime time.Time `json:"StartDateTime"`
	EndDateTime time.Time `json:"EndDateTime"`
	Alerts int32 `json:"Alerts,omitempty"`
	SlaTarget float64 `json:"SlaTarget,omitempty"`
	SlaTargetTotalTime float64 `json:"SlaTargetTotalTime,omitempty"`
	OperatorResponseTarget float64 `json:"OperatorResponseTarget,omitempty"`
	OperatorResponseTime float64 `json:"OperatorResponseTime,omitempty"`
	DowntimePercentage float64 `json:"DowntimePercentage,omitempty"`
	UptimePercentage float64 `json:"UptimePercentage,omitempty"`
	Checks int64 `json:"Checks,omitempty"`
	ConfirmedErrors int32 `json:"ConfirmedErrors,omitempty"`
	UnconfirmedErrors int32 `json:"UnconfirmedErrors,omitempty"`
	Uptime int64 `json:"Uptime,omitempty"`
	Downtime int64 `json:"Downtime,omitempty"`
	TotalTime float32 `json:"TotalTime,omitempty"`
	ResolveTime float32 `json:"ResolveTime,omitempty"`
	ConnectionTime float32 `json:"ConnectionTime,omitempty"`
	DownloadTime float32 `json:"DownloadTime,omitempty"`
	TotalBytes int64 `json:"TotalBytes,omitempty"`
}
